### ISSUE TITLE
VexFlow

### ISSUE THREAD

**Issue by rvilarl** [stringsync/musicxml#1]
Hi Jared,
I saw your proposal in OSMD. Have you considered using VexFlow directly?

**Comment by jaredjj3** [comment]
Thanks for the suggestion! Yes, that was my original approach years ago, but it wasn't maintainable. I also tried making a [VexTab](https://vexflow.com/vextab/) editor, but VexTab is an incomplete language - I couldn't express a lot of basic notations with it.

That's where OSMD came in. I knew that software such as GuitarPro that could export MusicXML, so I could leverage their editing interfaces, export MusicXML, and then render it in a browser with OSMD. This solved my maintainability problem using VexFlow or VexTab directly. MusicXML is also a standard way to store music score data, so this ultimately finalized my trajectory.

In my main project, [stringsync](https://stringsync.com), there are some sought-after features that require me to change the MusicXML (e.g. show only tabs, only notation, or both). I also want the application to eventually be able to edit music scores within the browser, so creating this library felt like the right move personally.

I'm happy to elaborate if you're curious about any specific details.

**Comment by rvilarl** [comment]
I started with https://github.com/rvilarl/pianoplay using OSMD I published it 2 months ago. I thought that it would be a good idea to collaborate with the lib as there were and are several bugs.
I started trying to collaborate with OSMD but it was very slow, it is really hard to get something accepted by Simon, he is very busy. I still collaborate though, I am trying to get a version using VexFlow 4.
Then I decided to collaborate with VexFlow and this was much more dynamic. We have ported VexFlow from JS to TS.

Why would OSMD be more adequated than VexFlow? OSMD uses VexFlow anyway (still version 1).

**Comment by rvilarl** [comment]
I would also like to get more info in the maintainability with VexFlow. I am trying to improve this lib now.

**Comment by jaredjj3** [comment]
I took a look at pianoplay and I'm impressed. I think it's a good showcase of what the OSMD library can do. I didn't know that browsers have a [MIDI API](https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API).

>Why would OSMD be more adequated than VexFlow? OSMD uses VexFlow anyway (still version 1).

The main selling point of MusicXML for me is that I have a stable schema for the data that is also compatible with other software. Since that is important to me, rendering MusicXML was my next highest priority. Since that process is already available in OSMD, it made more sense for me to use OSMD instead of VexFlow. I see that VexFlow has a newish offering called EasyScore, but it does not give me a way to serialize data that's compatible with other software.

I need a low barrier to entry for users to import music they've transcribed with other software. MusicXML + OSMD facilitates that.

>I would also like to get more info in the maintainability with VexFlow. I am trying to improve this lib now.

If VexFlow could render MusicXML, I would not have a reason to use OSMD. The [VexFlow wiki](https://github.com/0xfe/vexflow/wiki/Import-MusicXML) highlights some efforts to render MusicXML with VexFlow. However, it's worth noting that [vexflow-musicxml](https://github.com/bneumann/vexflow-musicxml) is discontinued in favor of opensheetmusicdisplay and [LeadsheetJS](https://github.com/SonyCSL-Paris/LeadsheetJS) 404s. opensheetmusicdisplay seems to be the canonical effort to render MusicXML using VexFlow, which is why I'm still compelled to use it and contribute to it.

EasyScore seems to fit a certain use case like a personal blog, where one-off transcriptions need to be rendered. As you know, making a music score transcription API is a highly complex problem. I'm not confident that EasyScore will ever really be able to accommodate all of the edge cases of MusicXML, which is why I'm reluctant to write anything on top of it (i.e. a MusicXML -> EasyScore parser).

What are your thoughts?

**Comment by rvilarl** [comment]
I also like EasyScore. Mohit, the owner of VexFlow, sees it, I believe, as a supporting tool for the Factory class. However I would be happy to expand it with good interface proposals from your side or anyone else. Mohit also works in Google by the way.

**Comment by jaredjj3** [comment]
I propose two additional abstractions:

- `MusicXMLParser`: This class is concerned with transforming a MusicXML string into a more JavaScript-compatible structure. For example, in `@stringsync/musicxml`, I use [xml-js](https://github.com/nashwaan/xml-js) to parse an XML string into a JavaScript object. Since the `xml-js` typings aren't great (most properties are optional), I do an additional [transformation](https://github.com/stringsync/musicxml/blob/569ded381b9ddbeddeb001fc9fd397053555f20e/src/lib/raw/parse.ts) on the `xml-js` output to get a structure that has a higher type strength. The [sax-js](https://github.com/isaacs/sax-js) library has a lower level offering that allows you to stream XML documents instead of trying to fit everything in memory like `xml-js`.

- `EasyScoreMessageBroker`: This class will take the structure from the `MusicXMLParser` and emit messages to an `EasyScore` instance. The messages will cause `EasyScore` to call its APIs to render the score. I don't think having a message abstraction is totally necessary, but it does decouple the `EasyScore` API from the `EasyScoreMessageBroker`.

This is a _very rough_ draft of what I'm envisioning:

```ts
type EasyScoreMessageReceiver = {
  onMessage(message: EasyScoreMessage);
};

class EasyScore {
  static fromMusicXml(containerId: string, musicXml: string): EasyScore {
    const easyScore = new EasyScore(containerId);
    EasyScoreMessageBroker.feed(musicXml).message(easyScore);
    return easyScore;
  }

  onMessage(message: EasyScoreMessage): void {
    // call APIs to render whatever the message/instruction is calling for
  }
}

class EasyScoreMessageBroker {
  static feed(musicXml: string) {
     const root = MusicXMLParser.parse(musicXml);
     return new EasyScoreMessageBroker(root);
  }

  private root: MusicXMLRootNode;
  private constructor(root: MusicXMLRootNode) {
    this.root = root;
  }

  message(receiver: EasyScoreMessageReceiver): void {
     const cursor = new MusicXMLCursor(this.root);
     while (cursor.hasNext()) {
       cursor.next();
       const node = cursor.get();
       const messages = this.getMessages(node);
       for (const message of message) {
         receiver.onMessage(message);
       }
     }
  }

  private getMessages(node: MusicXMLNode): EasyScoreMessage[] {}
}

class MusicXMLCursor {
  root: MusicXMLRootNode;
  node: MusicXMLNode | null;
  constructor(root: MusicXMLRootNode) {
    this.root = root;
    this.node = null;
  }

  get(): MusicXMLNode {}
  hasNext(): boolean {}
  next(): void {}
}
```

**Comment by rvilarl** [comment]
You mean adding this abstractions to VexFlow, do not you? Or is it a thirp app using stringsync/musicxml and vexflow.

It would make sense to do a POC first, how do we do that?

**Comment by jaredjj3** [comment]
I’m proposing to add a system like that to VexFlow as a way for it to directly support rendering MusicXML without having to ~change~ remove any existing API.

A POC would be to render a single measure of quarter notes, similar to the examples in the VexFlow README. I will caution that it would be a lot of work (hours to days) still.

**Comment by rvilarl** [comment]
Proposal above understood, but how would that interact with your library?

**Comment by jaredjj3** [comment]
It wouldn’t - it would obsolete this library for my purposes. The problem with this library is that it’s a large bundle (800kB minified and 50kB minified+gunzipped), so I wouldn’t try to make it a VexFlow dependency.

However, the more I think about it, the solution I proposed might grow to be a similar size.

I think we could arrive to a POC by hard coding some of the return values of the interfaces here. Where do you think is a good place to collaborate on this? JSFiddle? A new repo?

**Comment by rvilarl** [comment]
Probably a new repo. I do not think that it would be that simple to handle on jsfiddle, but perhaps I am wrong.

**Comment by jaredjj3** [comment]
Let's use stackblitz. It's easy to make a repo from the project if needed. I'll try to revisit this in the near future, you can fork off of this after I have something more concrete: https://stackblitz.com/edit/typescript-fbkn55?file=index.ts. I'll update you here.

edit: For now, I'm calling it `vexml`. Repo is here: https://github.com/jaredjj3/vexml/tree/master, but you can still use the stackblitz link.

**Comment by rvilarl** [comment]
I have never used stackblitz :). Do you set me as contributor in vexml or do you want me to fork?

**Comment by jaredjj3** [comment]
I added you as a contributor.

**Comment by rvilarl** [comment]
I think that we can continue discussing topics in the new repo.
